services:
  nginx_proxy:
    image: nginx:latest
    ports:
      - "7080:80"
      - "7443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs/webte_fei_stuba_sk.pem:/etc/nginx/certs/webte_fei_stuba_sk.pem
      - ./docker/nginx/certs/webte.fei.stuba.sk.key:/etc/nginx/certs/webte.fei.stuba.sk.key
    depends_on:
      phpmyadmin:
        condition: service_started
      frontend:
        condition: service_started
      backend:
        condition: service_started
      php:
        condition: service_started
  backend:
    image: nginx:latest
    volumes:
      - ./docker/nginx/backend.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www/html
    depends_on:
      php:
        condition: service_started
  php:
    image: "backendphp"
    build: 
      context: ./backend
      args:
          - UID=${UID:-1000}
          - GID=${GID:-1000}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
  db:
    image: mysql:8.3.0
    restart: always
    volumes:
      - webte_mysql:/var/lib/mysql
      - ./db/export:/docker-entrypoint-initdb.d
      - ./docker/mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: "WebteFinal123[]"
      MYSQL_USER: "webte"
      MYSQL_PASSWORD: "WebteFinal123[]"
      MYSQL_DATABASE: "laravel"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 120s
      retries: 25
      interval: 5s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: ${APP_URL}/phpmyadmin/
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      args:
        - BUILD_ENV=production
        - VITE_API_URL=${APP_URL}:7080/api/
volumes:
  webte_mysql: